# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_app
spring.datasource.username=postgres
spring.datasource.password=5868

# JPA + Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server context path
server.servlet.context-path=/api/v1.0

# AWS S3
aws.access.key=your_access_key
aws.secret.key=your_secret_key
aws.region=ap-south-1
aws.bucket.name=your_bucket_name

# JWT
jwt.secret.key=thisismysecretkeyfortheupcomingproject

# Razorpay
razorpay.key.id=your_key_id
razorpay.key.secret=your_secret_key
